
FROM anapsix/alpine-java
MAINTAINER mmerhav 
CMD echo 'RemoteControlServer Docker build initiating...'
COPY remote-control-server-1.5.0-exec.jar /home/remote-control-server-1.5.0-exec.jar
CMD ["java","-jar","/home/remote-control-server-1.5.0-exec.jar"]
